version: '3'

services:
  db:
    container_name: db-xplo-test
    image: postgres
    cap_add:
      - SYS_NICE
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./data/docker/postgresql:/var/lib/postgresql/data
